# Gemini
model: gemini/gemini-2.5-pro-preview-03-25

# openai
# model: o4-mini
# editor-model: gpt-4.1
# reasoning-effort: medium
# editor-edit-format: patch

architect: true

# Git
auto-commits: false
gitignore: false

# Lint
lint: false
auto-lint: false

# Theme
dark-mode: true
# Fix autocomplete menu not readable
completion-menu-color: "#cdd6f4"
completion-menu-bg-color: "#1e1e2e"
completion-menu-current-color: "#45475a"
completion-menu-current-bg-color: "#f9e2af"
