#!/usr/bin/env bash
APT_PACKAGES=(
	# Basic
	sudo
	stow
	flatpak
	# SwayWM
	sway
	swaybg
	waybar
	swaylock
	sway-notification-center
	network-manager
	wofi
	pulseaudio-utils
	playerctl
	grim
	slurp
	imv
	mpv
	xwayland
	xdg-desktop-portal-wlr # Screen recording
	xdg-desktop-portal-gtk # Flatpak integrations like file laucher
	xdg-user-dirs
	# Utils
	zsh
	git
	wget
	curl
	gnupg
	exa
	htop
	ca-certificates
	# Applications
	thunar
	thunar-archive-plugin
	thunar-volman
	pavucontrol
	alacritty
	keepassxc
	meld
	gimp
)

FLATPAK_PACKAGES=(
	org.mozilla.firefox
	org.chromium.Chromium
	com.sublimetext.three
	com.jetbrains.PyCharm-Professional
	io.dbeaver.DBeaverCommunity
	com.slack.Slack
)


sudo apt update
sudo apt install --assume-yes ${APT_PACKAGES[@]}


# Flatpak
flatpak remote-add --if-not-exists --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo
flatpak install -y --user flathub ${FLATPAK_PACKAGES[@]}


# Docker
sudo install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --yes --dearmor -o /etc/apt/keyrings/docker.gpg
sudo chmod a+r /etc/apt/keyrings/docker.gpg
echo \
  "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
  "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update
sudo apt-get install --assume-yes docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
sudo usermod -aG docker $USER


# Install ly display manager
git clone --recurse-submodules https://github.com/fairyglade/ly /tmp/fly
(
	cd /tmp/fly
	make
	sudo make install installsystemd
)
sudo systemctl enable ly.service
rm -rf /tmp/fly

# Make ZSH the default
sudo chsh -s $(which zsh) $USER

# Install oh-my-zsh
git clone https://github.com/ohmyzsh/ohmyzsh.git ~/.oh-my-zsh

# Install starship
wget --quiet --output-document=/tmp/starship.tar.gz https://github.com/starship/starship/releases/latest/download/starship-x86_64-unknown-linux-musl.tar.gz
sudo tar -xzof /tmp/starship.tar.gz -C /usr/local/bin
rm /tmp/starship.tar.gz

# Setup git config
git config --global core.editor "nano -w"
git config --global fetch.prune true
git config --global pull.rebase true
git config --global push.default current

# Finisch youtube music setup
./bin/.local/scripts/create-firefox-youtube-music-profile

# Symlink dot files
./install