#!/usr/bin/env bash

# Exit on error
set -e
# Print the command
set -x

ZYPPER_PACKAGES=(
	# Basic
	ca-certificates
	sudo
	stow
	flatpak
	python311-pipx
	nodejs-common
	patterns-devel-base-devel_basis
	hack-fonts
	google-noto-coloremoji-fonts
	libopenssl-devel # Needed for taplo (TOML LSP)
	# Display manager
	greetd
	tuigreet
	# Desktop environment (SwayWM + application)
	sway
	swaybg
	waybar
	swaylock
	SwayNotificationCenter
	clipman
	wl-clipboard
	brightnessctl
	polkit-gnome # Allow gui apps to ask root password
	xhost # Allow xwayland gui apps to use root password
	gnome-keyring # Secret store for other apps
	seahorse # keyring manager
	kanshi # Auto display manager
	pipewire # Audio
	NetworkManager
	bluez
	bluetuith
	fuzzel
	playerctl
	grim
	slurp
	imv
	mpv
	xwayland
	xdg-desktop-portal-wlr # Screen recording
	xdg-desktop-portal-gtk # Flatpak integrations like file laucher
	xdg-user-dirs
	# CLI tools
	zsh
	starship
	git
	rustup
	git-delta
	wget
	curl
	gnupg
	eza
	htop
	fzf
	fd
	helix
	ShellCheck
	zellij
	shfmt # Used by bash LSP for formatting
	calc
	chafa
	bat
	xh
	jq
	# GUI Applications
	MozillaFirefox
	chromium
	libreoffice
	thunar
	thunar-archive-plugin
	thunar-volman
	pavucontrol
	alacritty
	keepassxc
	meld
	gimp
)

FLATPAK_PACKAGES=(
	io.dbeaver.DBeaverCommunity
	com.slack.Slack
)


sudo zypper update
sudo zypper install --no-confirm "${ZYPPER_PACKAGES[@]}"


# Flatpak
flatpak remote-add --if-not-exists --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo
flatpak install -y --user flathub "${FLATPAK_PACKAGES[@]}"

# Docker
sudo zypper install --no-confirm docker docker-compose
sudo systemctl enable docker
sudo usermod -G docker -a "$USER"


# Enable and configure greetd+tuigreet
sudo mkdir /var/cache/tuigreet
sudo chown greeter:greeter /var/cache/tuigreet
sudo chmod 0755 /var/cache/tuigreet
sudo tee /etc/greetd/config.toml << EOF
[terminal]
vt = 1

[default_session]
command = "tuigreet --time --remember --asterisks --cmd sway"
user = "greeter"
EOF
# Fix log spam on screen: https://github.com/apognu/tuigreet/issues/68
sudo mkdir -p /etc/systemd/system/greetd.service.d/
sudo tee /etc/systemd/system/greetd.service.d/no_spam.conf << EOF
[Service]
Type=idle
StandardInput=tty
StandardOutput=tty
StandardError=journal
TTYReset=true
TTYVHangup=true
TTYVTDisallocate=true
EOF
sudo systemctl set-default graphical.target
sudo systemctl enable greetd

# Enable gnome keyring
systemctl enable --user gnome-keyring-daemon

# Make ZSH the default
sudo chsh -s "$(which zsh)" "$USER"


# Install oh-my-zsh
git clone https://github.com/ohmyzsh/ohmyzsh.git ~/.oh-my-zsh


# Setup git config
git config --global init.defaultBranch main
git config --global core.excludesFile '~/.git-global-ignore'
git config --global core.editor helix
git config --global core.pager delta
git config --global interactive.difffilter "delta --color-only --features=interactive"
git config --global merge.conflictstyle diff3
git config --global diff.colorMoved default
git config --global include.path ~/.catppuccin.gitconfig
git config --global delta.line-numbers true
git config --global delta.hunk-header-style omit
git config --global delta.features catppuccin-mocha
git config --global delta.dark true
git config --global fetch.prune true
git config --global pull.rebase true
git config --global push.default current
git config --global alias.lgm "log --merges --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"

# Setup rust
rustup default stable
rustup component add rust-analyzer
cargo install cargo-update

# Setup npm
mkdir -p "${HOME}/.npm-packages"
npm config set prefix "${HOME}/.npm-packages"


# Setup helix
helix --grammar fetch
helix --grammar build
# LSP: Pyhon
pipx install "python-lsp-server[all]"
pipx inject python-lsp-server python-lsp-black
pipx inject python-lsp-server python-lsp-isort
# LSP: HTML, CSS, JSON, eslint
npm install -g vscode-langservers-extracted
# LSP: Django template
pipx install django-template-lsp
# Formattter: Django template
pipx install djlint
# LSP: htmx
cargo install htmx-lsp
# LSP: Typescript/Javascript
npm install -g typescript-language-server typescript
# LSP: YAML
npm install -g yaml-language-server
# LSP: Dockerfile
npm install -g dockerfile-language-server-nodejs
# LSP: docker-compose
npm install -g @microsoft/compose-language-service
# LSP: Bash
npm i -g bash-language-server
# LSP: toml
cargo install taplo-cli --locked --features lsp
# LSP: Markdown
curl -L https://github.com/artempyanykh/marksman/releases/download/2024-12-18/marksman-linux-x64 > "$HOME/.local/bin/marksman"
chmod +x "$HOME/.local/bin/marksman"
# SQL: LSP/Formatter
npm install -g sql-language-server
pipx install sqlfluff

# Install aider
pipx install aider-chat

# Install pgcli
pipx install pgcli

# Install posting
pipx install posting

# Install yazi
cargo install --locked yazi-fm yazi-cli

# Install ollama
mkdir ~/opt/ollama
tar -C ~/opt/ollama -xzf ollama-linux-amd64.tgz
rm ollama-linux-amd64.tgz
mkdir -p ~/.local/bin
ln -s ~/opt/ollama/bin/ollama ~/.local/bin/ollama

# Finisch youtube music setup
./bin/.local/scripts/create-firefox-youtube-music-profile

# Make firefox default browser
xdg-settings set default-web-browser firefox.desktop

# Remove motd message
sudo rm /usr/lib/motd.d/welcome


# Symlink dot files
./create_symlinks

# Build bat themes
bat cache --build

# Enable ollama
systemctl --user daemon-reload
systemctl --user enable ollama
