#!/usr/bin/env bash
STOW_FOLDERS=(
    alacritty
    applications
    bin
    fonts
    mpv
    starship
    sway
    swaylock
    swaync
    user-dirs
    waybar
    wofi
    zsh
)


mkdir -p \
  ~/.config \
  ~/Documents \
  ~/Downloads \
  ~/Music \
  ~/Pictures \
  ~/Videos


for folder in "${STOW_FOLDERS[@]}"
do
  echo "stow $folder"
  stow $folder
done
