theme = "catppuccin_mocha"

[editor]
line-number = "relative"
color-modes = true
cursorline = true
auto-save = true
auto-format = false
undercurl = true
completion-timeout = 5
completion-trigger-len = 1
end-of-line-diagnostics = "hint"

[editor.file-picker]
hidden = false

[editor.lsp]
auto-signature-help = false
display-inlay-hints = false


[editor.indent-guides]
render = true

[editor.inline-diagnostics]
cursor-line = "warning"

[keys.normal."space"]
u = ":reset-diff-change"
n = ":sh ~/.config/helix/open-yazi-picker.sh"
