theme = "catppuccin_mocha"

[editor]
line-number = "relative"
color-modes = true
cursorline = true
auto-save = true
auto-format = false
undercurl = true

[editor.file-picker]
hidden = false

[editor.lsp]
auto-signature-help = false
display-inlay-hints = false


[editor.indent-guides]
render = true

[keys.normal."space"]
u = ":reset-diff-change"
