theme = "catppuccin_mocha"

[editor]
line-number = "relative"
auto-save = true
undercurl = true

[editor.file-picker]
hidden = false

[editor.lsp]
auto-signature-help = true
display-inlay-hints = false


[editor.indent-guides]
render = true

