[language-server.pylsp.config.pylsp.plugins]
jedi = {environment = "env"}
flake8 = {enabled = true, maxLineLength = 88}
# Disable rope_autimport, make startup slow and invalid import path for env variable 
#rope_autoimport = {enabled = true, memory=true}
rope_autoimport = {enabled = false}
autopep8 = {enabled = false}
mccabe = {enabled = false}
pycodestyle = {enabled = false}
pyflakes = {enabled = false}
pylint = {enabled = false}
yapf = {enabled = false}
ruff = { enabled = false}

[[language]]
name = "htmldjango"
scope = "source.htmldjango"
injection-regex = "htmldjango"
roots = []
file-types = [ "html" ]
indent = { tab-width = 2, unit = "  " }
language-servers = [ "vscode-html-language-server" ]

[[grammar]]
name = "htmldjango"
source = { git = "https://github.com/interdependence/tree-sitter-htmldjango" , rev = "ea71012d3fe14dd0b69f36be4f96bdfe9155ebae" }
