[language-server.djlsp]
command = "djlsp"

[language-server.sql-language-server]
command = "sql-language-server"
args = ["up", "--method", "stdio"]

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]
config = { harper-ls = { diagnosticSeverity = "warning", linters = { LongSentences = false } } }

[language-server.pylsp.config.pylsp.plugins]
jedi = { environment = "env" }
flake8 = { enabled = true, maxLineLength = 88 }
# Disable rope_autimport, make startup slow and invalid import path for env variable 
#rope_autoimport = {enabled = true, memory=true}
rope_autoimport = { enabled = false }
autopep8 = { enabled = false }
mccabe = { enabled = false }
pycodestyle = { enabled = false }
pyflakes = { enabled = false }
pylint = { enabled = false }
yapf = { enabled = false }
ruff = { enabled = false }


[[language]]
name = "python"
language-servers = ["pylsp", "harper-ls"]


[[language]]
name = "javascript"
language-servers = ["typescript-language-server", "harper-ls"]


[[language]]
name = "htmldjango"
scope = "source.htmldjango"
injection-regex = "htmldjango"
roots = []
file-types = ["html"]
indent = { tab-width = 2, unit = "  " }
language-servers = ["djlsp", "vscode-html-language-server"]
formatter = { command = "djlint", args = [
  "--reformat",
  "--profile=django",
  "--indent=2",
  "--blank-line-after-tag=load,extends,include,endblock",
  "--format-css",
  "--format-js",
  "-",
] }

[language.auto-pairs]
'"' = '"'
'(' = ')'
'[' = ']'
'{' = '}'
'%' = '%'
'<' = '>'

[[grammar]]
name = "htmldjango"
source = { git = "https://github.com/interdependence/tree-sitter-htmldjango", rev = "ea71012d3fe14dd0b69f36be4f96bdfe9155ebae" }


[[language]]
name = "markdown"
language-servers = ["marksman", "harper-ls"]

[[language]]
name = "git-commit"
language-servers = ["harper-ls"]

[[language]]
name = "sql"
language-servers = ["sql-language-server"]
formatter = { command = "sqlfluff", args = [
  "format",
  "--dialect",
  "postgres",
  "-",
] }
